"""add outbound messages, outbox jobs, local sink emails for milestone 2

Revision ID: 310beeb762b4
Revises: e7db6f2463e8
Create Date: 2026-09-21 09:36:34.209573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310beeb762b4'
down_revision: Union[str, Sequence[str], None] = 'e7db6f2463e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_sink_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_sink_emails_id'), 'local_sink_emails', ['id'], unique=False)
    op.create_index(op.f('ix_local_sink_emails_idempotency_key'), 'local_sink_emails', ['idempotency_key'], unique=True)
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'sent', 'failed', 'bounced', name='messagestatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_recipient_email', sa.String(), nullable=True),
    sa.Column('approved_subject', sa.String(), nullable=True),
    sa.Column('approved_body', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_id'), 'outbound_messages', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_ticket_id'), 'outbound_messages', ['ticket_id'], unique=False)
    op.create_table('outbox_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_key', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'claimed', 'sent', 'failed', 'ambiguous', name='outboxjobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('leased_by', sa.String(), nullable=True),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['outbound_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_outbox_jobs_id'), 'outbox_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_operation_key'), 'outbox_jobs', ['operation_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_jobs_operation_key'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_id'), table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    op.drop_index(op.f('ix_outbound_messages_ticket_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_local_sink_emails_idempotency_key'), table_name='local_sink_emails')
    op.drop_index(op.f('ix_local_sink_emails_id'), table_name='local_sink_emails')
    op.drop_table('local_sink_emails')
    # ### end Alembic commands ###
    # NOT auto-generated - added after a real failure found by actually
    # testing downgrade-then-upgrade against Postgres (SQLite never hit
    # this: it has no native enum type, so this class of bug is
    # invisible there). On Postgres, sa.Enum(...) creates a separate
    # named TYPE alongside the table - dropping the table does NOT drop
    # the type, so re-running upgrade() afterward fails with "type
    # already exists" on the CREATE TYPE statement.
    #
    # This is guarded to Postgres only, not run unconditionally: SQLite
    # has no DROP TYPE statement at all and raises a syntax error on it
    # (confirmed directly - `sqlite3.OperationalError: near "TYPE":
    # syntax error` - rather than assumed to no-op, which was wrong).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS messagestatus")
        op.execute("DROP TYPE IF EXISTS outboxjobstatus")
