"""add calls table for milestone 3 telephony

Revision ID: 9dc34cdde31d
Revises: 310beeb762b4
Create Date: 2026-09-21 20:03:18.883581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc34cdde31d'
down_revision: Union[str, Sequence[str], None] = '310beeb762b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='calldirection'), nullable=False),
    sa.Column('from_number', sa.String(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ringing', 'in_progress', 'completed', 'failed', 'busy', 'no_answer', 'canceled', name='callstatus'), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_ticket_id'), 'calls', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_calls_twilio_call_sid'), 'calls', ['twilio_call_sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_twilio_call_sid'), table_name='calls')
    op.drop_index(op.f('ix_calls_ticket_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
    # NOT auto-generated - applying the same fix Milestone 2's migration
    # needed (see that revision's own comment): on Postgres, sa.Enum(...)
    # creates a separate named TYPE that DROP TABLE doesn't remove, so a
    # later upgrade's CREATE TYPE fails with "already exists" otherwise.
    # Guarded to Postgres only - SQLite has no DROP TYPE statement and
    # raises a syntax error on it (confirmed directly when this exact
    # guard was first added).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS calldirection")
        op.execute("DROP TYPE IF EXISTS callstatus")
