"""add queued to callstatus enum for outbound calling

Revision ID: a3f1c9e7b2d4
Revises: 9dc34cdde31d
Create Date: 2026-09-21 22:35:00.000000

Written by hand, not autogenerated - Alembic's autogenerate does not
detect enum VALUE additions (only whole-column type changes), and a
Postgres native enum's ADD VALUE has a real operational requirement
autogenerate wouldn't produce correctly anyway: it must run outside the
migration's normal transaction block (a Postgres restriction on
ALTER TYPE ... ADD VALUE - see op.get_context().autocommit_block()
below). Confirmed this was actually necessary, not just cautious, by
testing directly: the native `callstatus` enum on a real Postgres
database rejected the raw string "queued" with
`invalid input value for enum callstatus: "queued"` before this
migration existed.
"""
from typing import Sequence, Union

from alembic import op


revision: str = 'a3f1c9e7b2d4'
down_revision: Union[str, Sequence[str], None] = '9dc34cdde31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # ALTER TYPE ... ADD VALUE cannot run inside the transaction
        # Alembic normally wraps each migration in - autocommit_block()
        # is Alembic's own documented mechanism for exactly this case.
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE callstatus ADD VALUE IF NOT EXISTS 'queued' BEFORE 'ringing'")
    # SQLite: no action needed. Its Enum column has no native type to
    # alter - confirmed directly (not assumed) that SQLite accepts an
    # unrecognized status string with zero enforcement, unlike Postgres.


def downgrade() -> None:
    # Postgres does not support removing a value from an existing enum
    # type at all (no ALTER TYPE ... DROP VALUE exists) - the only way
    # to reverse this would be recreating the entire `callstatus` type,
    # which risks data loss for any row already using 'queued' and is
    # not attempted here. This is a real, accepted limitation of
    # Postgres enums, not an oversight: the 'queued' label remains
    # after downgrade, which is harmless (an unused valid enum value).
    pass
