"""add lease_token to outbox_jobs for safe worker crash recovery

Revision ID: e38103fdb554
Revises: a3f1c9e7b2d4
Create Date: 2026-09-24 00:10:04.916267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38103fdb554'
down_revision: Union[str, Sequence[str], None] = 'a3f1c9e7b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_jobs', sa.Column('lease_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_jobs', 'lease_token')
    # ### end Alembic commands ###
