"""add customers, contacts, audit events; ticket customer/assignee/version

Revision ID: e7db6f2463e8
Revises: 7420c85d3ce8
Create Date: 2026-09-21 06:28:07.829566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7db6f2463e8'
down_revision: Union[str, Sequence[str], None] = '7420c85d3ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('normalized_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_customer_id'), 'contacts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_phone'), 'contacts', ['normalized_phone'], unique=False)
    # batch_alter_table (not plain op.add_column/create_foreign_key) is
    # required here, not just tidier: SQLite has no ALTER TABLE support
    # for adding constraints to an existing table - Alembic's SQLite
    # dialect raises NotImplementedError without it. Batch mode does a
    # copy-and-recreate under the hood on SQLite, and is a thin,
    # equivalent wrapper around native ALTER TABLE on Postgres - the
    # same migration file genuinely works on both, which was verified
    # by actually running it against both (see docs/current-state.md).
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        # server_default='1' matters here, not just style: this is a NOT
        # NULL column being added to a table that may already have rows
        # (existing tickets) - without a default, both SQLite and
        # Postgres reject the ALTER TABLE outright. '1' matches the
        # Python-side model default (Ticket.version = Column(...,
        # default=1)) so existing tickets start at the same version a
        # brand-new one would.
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_index(batch_op.f('ix_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_tickets_customer_id', 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key('fk_tickets_assignee_id', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_assignee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_tickets_customer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_assignee_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('customer_id')
    op.drop_index(op.f('ix_contacts_normalized_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_customer_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
